autoSectionPath = "src"
changelog = true
gitSourceBranch = "main"
title = "Data Structures"

[docusaurus]
baseUrl = "/data-structures"
tagline = "A collection of data structures aimed specifically at Roblox game development."

# [[navbar.items]]

[home]
enabled = true
includeReadme = false

[[home.features]]
description = "These data structures are designed to be as fast as possible, so that way your bottleneck should never be the library."
title = "High Performance"

[[home.features]]
description = "The data structures here are documented so that way there is never any confusion."
title = "Documentation"

[[home.features]]
description = "Since Luau is a typed language, these data structures are typed so that you will reduce the amount of bugs caused by type errors."
title = "Strict Typing"

[[home.features]]
description = "For added protections against mistakes, you can enable the global ultra strict mode flag to get more errors."
title = "Ultra Strict Mode"

[footer]
copyright = "Copyright © 2024 Bura Games. Made with Moonwave."
